### PR TITLE
Quasi pseudo-code for discussion

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
Introduces the mocked up pseudocode of the proposed visualization API for discussion.

---
This change is [Reviewable](https://reviewable.io/reviews/seancurtis-tri/drake/1)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
\cc @calderpg-tri

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/seancurtis-tri/drake/1)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @SeanCurtis-TRI)

___
*[proposed_vis.cc, line 57 at r1](https://reviewable.io/reviews/seancurtis-tri/drake/1#-LXy9vSK8Dk6JHr4dXz_:-LXy9vSK8Dk6JHr4dXza:bkq449l) ([raw file](https://github.com/seancurtis-tri/drake/blob/42adb43b2737826837fee99c0c9f4e3ce2990ce8/proposed_vis.cc#L57)):*
> ```cpp
> 
>   const int frame_count = frames.size() +
>       anchored_geometries.size() > 0 ? 1 : 0;
> ```

Uh... This logic's a bit confusing. Can you comment on why this is necessary?

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/seancurtis-tri/drake/1)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI)

___
*[proposed_vis.cc, line 57 at r1](https://reviewable.io/reviews/seancurtis-tri/drake/1#-LXy9vSK8Dk6JHr4dXz_:-LXyD4KK5gABWFMSGdwt:bp23c9z) ([raw file](https://github.com/seancurtis-tri/drake/blob/42adb43b2737826837fee99c0c9f4e3ce2990ce8/proposed_vis.cc#L57)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Uh... This logic's a bit confusing. Can you comment on why this is necessary?
</blockquote></details>

It's stolen from the LCM stuff where a world frame is only introduced if there are geometries affixed to the world frame. 

Based on that, I've designed the architecture to explicitly call out geometries affixed to the world frame vs those affixed to moving frames. If a particular application doesn't make that distinction, they can simply treat the anchored geometries (and the corresponding world frame) the same as any other frame. With the caveat that the world's frame will never be updated.

If you have a quesiton about anything, I'd advise first looking at the `geometry_visualization.cc` -- I indicated in the comments in the google doc that this example code was a reframing of that fucntionality.

**Comment by EricCousineau-TRI** [comment]
Hm... Going through my inbox, stumbled on this.
Should we close this one?

esp. in light of https://github.com/EricCousineau-TRI/repro/pull/1

**Comment by SeanCurtis-TRI** [comment]
Closed

**Pull request closed without merging**
