### PR TITLE
Python bindings

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
This extends the python bindings to include:

  - pydrake.geometry.render with
    - DepthCameraPropeties, RenderEngine, RenderEngineVtk
  - pydrake.systems.sensors with
    - RgbdSensor, RgbdSensorDiscrete

TODO:
  - Should I be introducing RenderEngineVtk? Or should I simply bind the
    factory?

---
This change is [Reviewable](https://reviewable.io/reviews/seancurtis-tri/drake/4)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/seancurtis-tri/drake/4)* status: 0 of 6 files reviewed, 1 unresolved discussion

___
*[bindings/pydrake/geometry_py.cc, line 77 at r1](https://reviewable.io/reviews/seancurtis-tri/drake/4#-Lgc1jDj8p5ERNRLHlb2:-Lgc1jDj8p5ERNRLHlb3:b-6edd6b) ([raw file](https://github.com/seancurtis-tri/drake/blob/b3c7f50814203ec48be8beaacf82c11a438b4443/bindings/pydrake/geometry_py.cc#L77)):*
> ```cpp
>   }
> 
>   {
> ```

This is most likely an error. I should be binding the construction parameters and the construction method.

**Comment by EricCousineau-TRI** [comment]
Answering questions:

> Should I be introducing RenderEngineVtk? Or should I simply bind the
factory?

I'd say let's just bind the factory for now - mimicking the public API?

**Review by EricCousineau-TRI — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/seancurtis-tri/drake/4)* status: 0 of 6 files reviewed, 5 unresolved discussions (waiting on @SeanCurtis-TRI)

___
*[bindings/pydrake/geometry_py.cc, line 77 at r1](https://reviewable.io/reviews/seancurtis-tri/drake/4#-Lgc1jDj8p5ERNRLHlb2:-Lgc6VLtEj3YfCDRAyr_:bqz8tkk) ([raw file](https://github.com/seancurtis-tri/drake/blob/b3c7f50814203ec48be8beaacf82c11a438b4443/bindings/pydrake/geometry_py.cc#L77)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

This is most likely an error. I should be binding the construction parameters and the construction method.
</blockquote></details>

Aye, sounds good to me.
___
*[bindings/pydrake/geometry_py.cc, line 88 at r1](https://reviewable.io/reviews/seancurtis-tri/drake/4#-Lgc6_pPCB_rbgfCGVHB:-Lgc6_pPCB_rbgfCGVHC:b-3hgf95) ([raw file](https://github.com/seancurtis-tri/drake/blob/b3c7f50814203ec48be8beaacf82c11a438b4443/bindings/pydrake/geometry_py.cc#L88)):*
> ```cpp
>         .def("is_reserved", &RenderLabel::is_reserved)
>         // EQ(==).
>         .def(py::self == RenderLabel())
> ```

Per prior discussions, should we also bind `py::self == int{}` and `int{} == py::self`?
(Same for `!=`?)
___
*[bindings/pydrake/geometry_py.cc, line 88 at r1](https://reviewable.io/reviews/seancurtis-tri/drake/4#-Lgc6oOQA6ZOzbskMjwY:-Lgc6oOQA6ZOzbskMjwZ:b5cvabz) ([raw file](https://github.com/seancurtis-tri/drake/blob/b3c7f50814203ec48be8beaacf82c11a438b4443/bindings/pydrake/geometry_py.cc#L88)):*
> ```cpp
>         .def("is_reserved", &RenderLabel::is_reserved)
>         // EQ(==).
>         .def(py::self == RenderLabel())
> ```

Note: This should actually be: `py::self == py::self` and `py::self != py::self`.
___
*[bindings/pydrake/systems/sensors_py.cc, line 193 at r1](https://reviewable.io/reviews/seancurtis-tri/drake/4#-Lgc5gvl3ARaxUPfZOiR:-Lgc5gvm3Qga4pDVPRan:bywwayl) ([raw file](https://github.com/seancurtis-tri/drake/blob/b3c7f50814203ec48be8beaacf82c11a438b4443/bindings/pydrake/systems/sensors_py.cc#L193)):*
> ```cpp
>   };
> 
>   py::class_<RgbdSensor, LeafSystem<T>> rgbd_sensor(m, "RgbdSensor");
> ```

Outside of context of Python bindings, but can I ask what the best way is for us to incorporate a (pending) decision from this PR?
https://github.com/RobotLocomotion/drake/pull/11337

Should I get this landed, and then can we use that in the dev porting?

Or should we just make a decision, and then you'll factor it into your decision?
___
*[bindings/pydrake/systems/sensors_py.cc, line 197 at r1](https://reviewable.io/reviews/seancurtis-tri/drake/4#-Lgc60qqBlin-PFWfHJg:-Lgc60qqBlin-PFWfHJh:bzbuf17) ([raw file](https://github.com/seancurtis-tri/drake/blob/b3c7f50814203ec48be8beaacf82c11a438b4443/bindings/pydrake/systems/sensors_py.cc#L197)):*
> ```cpp
>       .def(py::init<string, const Vector3d&, const RollPitchYawd&,
>                const DepthCameraProperties&, bool>(),
>           py::arg("name"), py::arg("p_WB_W"), py::arg("rpy_WB_W"),
> ```

Design nit: I would *love* it if we *only* exposed `RigidTransform`; sugar overloads of XYZ+RPY are from ye olde `RgbdCamera` design of @kunimatsu-tri that I don't agree with, and would prefer that we minimize the number of entry points to start.

(Sure, we can add it in later, but meh.)
___
*[bindings/pydrake/systems/sensors_py.cc, line 199 at r1](https://reviewable.io/reviews/seancurtis-tri/drake/4#-Lgc6OhN2Kh7Ek9tJLc-:-Lgc6OhN2Kh7Ek9tJLc0:bdwso01) ([raw file](https://github.com/seancurtis-tri/drake/blob/b3c7f50814203ec48be8beaacf82c11a438b4443/bindings/pydrake/systems/sensors_py.cc#L199)):*
> ```cpp
>           py::arg("name"), py::arg("p_WB_W"), py::arg("rpy_WB_W"),
>           py::arg("properties"), py::arg("show_window") = false,
>           doc.RgbdSensor.ctor.doc_5args_name_p_WB_W_rpy_WB_W_properties_show_window)
> ```

BTW See what happens when we have huge overloads? ;)

**Review by EricCousineau-TRI — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/seancurtis-tri/drake/4)* status: 0 of 6 files reviewed, 6 unresolved discussions (waiting on @SeanCurtis-TRI)

___
*[bindings/pydrake/geometry_py.cc, line 74 at r1](https://reviewable.io/reviews/seancurtis-tri/drake/4#-Lgc76l902DmDgsJrtMu:-Lgc76l902DmDgsJrtMv:brypygf) ([raw file](https://github.com/seancurtis-tri/drake/blob/b3c7f50814203ec48be8beaacf82c11a438b4443/bindings/pydrake/geometry_py.cc#L74)):*
> ```cpp
>   {
>     using Class = RenderEngine;
>     py::class_<Class>(m, "RenderEngine");
> ```

Hm... Is it possible to expose more of `RenderEngine`?

Would be nice to make rendering requests without having to assemble systems and query ports if I don't want to have to deal with Systems framework indirection noise.

**Review by SeanCurtis-TRI — COMMENTED** [review]
@ericcousineau-tri, you rock!  I'll go over this a bit later and may have some questions. But I appreciate the quick once over.

> *[Reviewable](https://reviewable.io/reviews/seancurtis-tri/drake/4#-:-Lgc54zc8mrx3H8wWztw:b99yptn)* status: 0 of 6 files reviewed, 6 unresolved discussions (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/seancurtis-tri/drake/4)* status: 0 of 6 files reviewed, 5 unresolved discussions (waiting on @EricCousineau-TRI and @kunimatsu-tri)

___
*[bindings/pydrake/geometry_py.cc, line 74 at r1](https://reviewable.io/reviews/seancurtis-tri/drake/4#-Lgc76l902DmDgsJrtMu:-Lh17D420Xe7wPGv14mb:b-b4hji0) ([raw file](https://github.com/seancurtis-tri/drake/blob/b3c7f50814203ec48be8beaacf82c11a438b4443/bindings/pydrake/geometry_py.cc#L74)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Hm... Is it possible to expose more of `RenderEngine`?

Would be nice to make rendering requests without having to assemble systems and query ports if I don't want to have to deal with Systems framework indirection noise.
</blockquote></details>

I'm going to defer this for now.

There are three public methods that will change when I kill the `RenderIndex` and `GeometryIndex`. It's easier to change and *then* bind then the other way around. And without those three methods (register, remove, and update poses), there's not a great deal of value in wrapping the rest. 
___
*[bindings/pydrake/geometry_py.cc, line 88 at r1](https://reviewable.io/reviews/seancurtis-tri/drake/4#-Lgc6_pPCB_rbgfCGVHB:-Lh1IqcBAeE8__FbNOTE:b-896fix) ([raw file](https://github.com/seancurtis-tri/drake/blob/b3c7f50814203ec48be8beaacf82c11a438b4443/bindings/pydrake/geometry_py.cc#L88)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Per prior discussions, should we also bind `py::self == int{}` and `int{} == py::self`?
(Same for `!=`?)
</blockquote></details>

Done.
___
*[bindings/pydrake/geometry_py.cc, line 88 at r1](https://reviewable.io/reviews/seancurtis-tri/drake/4#-Lgc6oOQA6ZOzbskMjwY:-Lh1JMPXBAngq4J-F4fF:bkamkby) ([raw file](https://github.com/seancurtis-tri/drake/blob/b3c7f50814203ec48be8beaacf82c11a438b4443/bindings/pydrake/geometry_py.cc#L88)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Note: This should actually be: `py::self == py::self` and `py::self != py::self`.
</blockquote></details>

Mind blown!  
___
*[bindings/pydrake/systems/sensors_py.cc, line 193 at r1](https://reviewable.io/reviews/seancurtis-tri/drake/4#-Lgc5gvl3ARaxUPfZOiR:-LiUxhBO--xKfemX6ScN:b-7x20hh) ([raw file](https://github.com/seancurtis-tri/drake/blob/b3c7f50814203ec48be8beaacf82c11a438b4443/bindings/pydrake/systems/sensors_py.cc#L193)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Outside of context of Python bindings, but can I ask what the best way is for us to incorporate a (pending) decision from this PR?
https://github.com/RobotLocomotion/drake/pull/11337

Should I get this landed, and then can we use that in the dev porting?

Or should we just make a decision, and then you'll factor it into your decision?
</blockquote></details>

In progress.
___
*[bindings/pydrake/systems/sensors_py.cc, line 197 at r1](https://reviewable.io/reviews/seancurtis-tri/drake/4#-Lgc60qqBlin-PFWfHJg:-LiUxvqd3ryuAGozTeEw:biqy0nw) ([raw file](https://github.com/seancurtis-tri/drake/blob/b3c7f50814203ec48be8beaacf82c11a438b4443/bindings/pydrake/systems/sensors_py.cc#L197)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Design nit: I would *love* it if we *only* exposed `RigidTransform`; sugar overloads of XYZ+RPY are from ye olde `RgbdCamera` design of @kunimatsu-tri that I don't agree with, and would prefer that we minimize the number of entry points to start.

(Sure, we can add it in later, but meh.)
</blockquote></details>

Done (plus, I really don't like RPY. I'm *much* better at good 'ol rotation matrices.)

**Comment by SeanCurtis-TRI** [comment]
This has served its purpose -- initial discussion held; real bindings have gone into drake.

**Pull request closed without merging**
